export {
    FETCH_SMURF_DATA,
    POST_SMURF_DATA,
    POST_SMURF_DATA_FAILED,
    POST_SMURF_DATA_SUCCESS,
    DELETE_SMURF,
    FETCH_SMURF_DATA_FAILED,
    FETCH_SMURF_DATA_SUCCESS,
    DELETE_SMURF_FAILED,
    DELETE_SMURF_SUCCESS,
    UPDATE_SMURF,
    UPDATE_SMURF_FAILED,
    UPDATE_SMURF_SUCCESS,
    updateSmurf,
    postData,
    getData,
    deleteSmurf
} from './smurfActions';