export {
    FETCH_SMURF_DATA,
    POST_SMURF_DATA,
    POST_SMURF_DATA_FAILED,
    POST_SMURF_DATA_SUCCESS,
    DELETE_SMURF,
    FETCH_SMURF_DATA_FAILED,
    FETCH_SMURF_DATA_SUCCESS,
    postData,
    getData
} from './smurfActions';